[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "fractaltoolkit"
description = "Python wrappers for the fractal-toolkit Fortran 90 library"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy", "f90wrap"]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "fractaltoolkit._version.__version__"}

[tool.setuptools]
package-dir = {"" = "build/pip"}
packages = ["fractaltoolkit"]

[tool.setuptools.package-data]
fractaltoolkit = ["*.so"]
